//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.30 at 03:52:53 PM CEST 
//


package ul.biotope.agents.brussels.jaxb.datex;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AccessEquipmentEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AccessEquipmentEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="barrier"/&gt;
 *     &lt;enumeration value="trafficSignal"/&gt;
 *     &lt;enumeration value="ticketButtonMachine"/&gt;
 *     &lt;enumeration value="ticketCardMachine"/&gt;
 *     &lt;enumeration value="payAndExitMachine"/&gt;
 *     &lt;enumeration value="other"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "AccessEquipmentEnum")
@XmlEnum
public enum AccessEquipmentEnum {

    @XmlEnumValue("barrier")
    BARRIER("barrier"),
    @XmlEnumValue("trafficSignal")
    TRAFFIC_SIGNAL("trafficSignal"),
    @XmlEnumValue("ticketButtonMachine")
    TICKET_BUTTON_MACHINE("ticketButtonMachine"),
    @XmlEnumValue("ticketCardMachine")
    TICKET_CARD_MACHINE("ticketCardMachine"),
    @XmlEnumValue("payAndExitMachine")
    PAY_AND_EXIT_MACHINE("payAndExitMachine"),
    @XmlEnumValue("other")
    OTHER("other");
    private final String value;

    AccessEquipmentEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AccessEquipmentEnum fromValue(String v) {
        for (AccessEquipmentEnum c: AccessEquipmentEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
