//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.30 at 03:52:53 PM CEST 
//


package ul.biotope.agents.brussels.jaxb.datex;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FuelType2Enum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FuelType2Enum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="all"/&gt;
 *     &lt;enumeration value="petrol95Octane"/&gt;
 *     &lt;enumeration value="petrol98Octane"/&gt;
 *     &lt;enumeration value="petrolLeaded"/&gt;
 *     &lt;enumeration value="petrolUnleaded"/&gt;
 *     &lt;enumeration value="unknown"/&gt;
 *     &lt;enumeration value="other"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "FuelType2Enum")
@XmlEnum
public enum FuelType2Enum {

    @XmlEnumValue("all")
    ALL("all"),
    @XmlEnumValue("petrol95Octane")
    PETROL_95_OCTANE("petrol95Octane"),
    @XmlEnumValue("petrol98Octane")
    PETROL_98_OCTANE("petrol98Octane"),
    @XmlEnumValue("petrolLeaded")
    PETROL_LEADED("petrolLeaded"),
    @XmlEnumValue("petrolUnleaded")
    PETROL_UNLEADED("petrolUnleaded"),
    @XmlEnumValue("unknown")
    UNKNOWN("unknown"),
    @XmlEnumValue("other")
    OTHER("other");
    private final String value;

    FuelType2Enum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FuelType2Enum fromValue(String v) {
        for (FuelType2Enum c: FuelType2Enum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
