//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.30 at 03:52:53 PM CEST 
//


package ul.biotope.agents.brussels.jaxb.datex;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GroupOfParkingSitesStatusEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="GroupOfParkingSitesStatusEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="allParkingsFull"/&gt;
 *     &lt;enumeration value="multiStoreyParkingsFull"/&gt;
 *     &lt;enumeration value="noMoreParkingSpacesAvailable"/&gt;
 *     &lt;enumeration value="enoughSpacesAvailable"/&gt;
 *     &lt;enumeration value="unknown"/&gt;
 *     &lt;enumeration value="other"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "GroupOfParkingSitesStatusEnum")
@XmlEnum
public enum GroupOfParkingSitesStatusEnum {

    @XmlEnumValue("allParkingsFull")
    ALL_PARKINGS_FULL("allParkingsFull"),
    @XmlEnumValue("multiStoreyParkingsFull")
    MULTI_STOREY_PARKINGS_FULL("multiStoreyParkingsFull"),
    @XmlEnumValue("noMoreParkingSpacesAvailable")
    NO_MORE_PARKING_SPACES_AVAILABLE("noMoreParkingSpacesAvailable"),
    @XmlEnumValue("enoughSpacesAvailable")
    ENOUGH_SPACES_AVAILABLE("enoughSpacesAvailable"),
    @XmlEnumValue("unknown")
    UNKNOWN("unknown"),
    @XmlEnumValue("other")
    OTHER("other");
    private final String value;

    GroupOfParkingSitesStatusEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static GroupOfParkingSitesStatusEnum fromValue(String v) {
        for (GroupOfParkingSitesStatusEnum c: GroupOfParkingSitesStatusEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
