//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.30 at 03:52:53 PM CEST 
//


package ul.biotope.agents.brussels.jaxb.datex;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GroupOfParkingSitesTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="GroupOfParkingSitesTypeEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="parkingArea"/&gt;
 *     &lt;enumeration value="truckParkingPriorityZone"/&gt;
 *     &lt;enumeration value="aggregationOfInformation"/&gt;
 *     &lt;enumeration value="inhabitantZone"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "GroupOfParkingSitesTypeEnum")
@XmlEnum
public enum GroupOfParkingSitesTypeEnum {

    @XmlEnumValue("parkingArea")
    PARKING_AREA("parkingArea"),
    @XmlEnumValue("truckParkingPriorityZone")
    TRUCK_PARKING_PRIORITY_ZONE("truckParkingPriorityZone"),
    @XmlEnumValue("aggregationOfInformation")
    AGGREGATION_OF_INFORMATION("aggregationOfInformation"),
    @XmlEnumValue("inhabitantZone")
    INHABITANT_ZONE("inhabitantZone");
    private final String value;

    GroupOfParkingSitesTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static GroupOfParkingSitesTypeEnum fromValue(String v) {
        for (GroupOfParkingSitesTypeEnum c: GroupOfParkingSitesTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
