//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.30 at 03:52:53 PM CEST 
//


package ul.biotope.agents.brussels.jaxb.datex;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LABELServiceLevelEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LABELServiceLevelEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="none"/&gt;
 *     &lt;enumeration value="serviceLevel1"/&gt;
 *     &lt;enumeration value="serviceLevel2"/&gt;
 *     &lt;enumeration value="serviceLevel3"/&gt;
 *     &lt;enumeration value="serviceLevel4"/&gt;
 *     &lt;enumeration value="serviceLevel5"/&gt;
 *     &lt;enumeration value="unknown"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "LABELServiceLevelEnum")
@XmlEnum
public enum LABELServiceLevelEnum {

    @XmlEnumValue("none")
    NONE("none"),
    @XmlEnumValue("serviceLevel1")
    SERVICE_LEVEL_1("serviceLevel1"),
    @XmlEnumValue("serviceLevel2")
    SERVICE_LEVEL_2("serviceLevel2"),
    @XmlEnumValue("serviceLevel3")
    SERVICE_LEVEL_3("serviceLevel3"),
    @XmlEnumValue("serviceLevel4")
    SERVICE_LEVEL_4("serviceLevel4"),
    @XmlEnumValue("serviceLevel5")
    SERVICE_LEVEL_5("serviceLevel5"),
    @XmlEnumValue("unknown")
    UNKNOWN("unknown");
    private final String value;

    LABELServiceLevelEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LABELServiceLevelEnum fromValue(String v) {
        for (LABELServiceLevelEnum c: LABELServiceLevelEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
