//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.30 at 03:52:53 PM CEST 
//


package ul.biotope.agents.brussels.jaxb.datex;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OpenlrOrientationEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OpenlrOrientationEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="noOrientationOrUnknown"/&gt;
 *     &lt;enumeration value="withLineDirection"/&gt;
 *     &lt;enumeration value="againstLineDirection"/&gt;
 *     &lt;enumeration value="both"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "OpenlrOrientationEnum")
@XmlEnum
public enum OpenlrOrientationEnum {

    @XmlEnumValue("noOrientationOrUnknown")
    NO_ORIENTATION_OR_UNKNOWN("noOrientationOrUnknown"),
    @XmlEnumValue("withLineDirection")
    WITH_LINE_DIRECTION("withLineDirection"),
    @XmlEnumValue("againstLineDirection")
    AGAINST_LINE_DIRECTION("againstLineDirection"),
    @XmlEnumValue("both")
    BOTH("both");
    private final String value;

    OpenlrOrientationEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OpenlrOrientationEnum fromValue(String v) {
        for (OpenlrOrientationEnum c: OpenlrOrientationEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
