//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.30 at 03:52:53 PM CEST 
//


package ul.biotope.agents.brussels.jaxb.datex;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ParkingSiteOvercrowdingStatusEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ParkingSiteOvercrowdingStatusEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="overcrowding"/&gt;
 *     &lt;enumeration value="noOvercrowding"/&gt;
 *     &lt;enumeration value="overcrowdingLevel1"/&gt;
 *     &lt;enumeration value="overcrowdingLevel2"/&gt;
 *     &lt;enumeration value="unknown"/&gt;
 *     &lt;enumeration value="other"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ParkingSiteOvercrowdingStatusEnum")
@XmlEnum
public enum ParkingSiteOvercrowdingStatusEnum {

    @XmlEnumValue("overcrowding")
    OVERCROWDING("overcrowding"),
    @XmlEnumValue("noOvercrowding")
    NO_OVERCROWDING("noOvercrowding"),
    @XmlEnumValue("overcrowdingLevel1")
    OVERCROWDING_LEVEL_1("overcrowdingLevel1"),
    @XmlEnumValue("overcrowdingLevel2")
    OVERCROWDING_LEVEL_2("overcrowdingLevel2"),
    @XmlEnumValue("unknown")
    UNKNOWN("unknown"),
    @XmlEnumValue("other")
    OTHER("other");
    private final String value;

    ParkingSiteOvercrowdingStatusEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ParkingSiteOvercrowdingStatusEnum fromValue(String v) {
        for (ParkingSiteOvercrowdingStatusEnum c: ParkingSiteOvercrowdingStatusEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
