//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.30 at 03:52:53 PM CEST 
//


package ul.biotope.agents.brussels.jaxb.datex;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ParkingTypeOfGroup.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ParkingTypeOfGroup"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="adjacentSpaces"/&gt;
 *     &lt;enumeration value="nonAdjacentSpaces"/&gt;
 *     &lt;enumeration value="completeFloor"/&gt;
 *     &lt;enumeration value="mixedUsage"/&gt;
 *     &lt;enumeration value="statisticsOnly"/&gt;
 *     &lt;enumeration value="singleParameters"/&gt;
 *     &lt;enumeration value="other"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ParkingTypeOfGroup")
@XmlEnum
public enum ParkingTypeOfGroup {

    @XmlEnumValue("adjacentSpaces")
    ADJACENT_SPACES("adjacentSpaces"),
    @XmlEnumValue("nonAdjacentSpaces")
    NON_ADJACENT_SPACES("nonAdjacentSpaces"),
    @XmlEnumValue("completeFloor")
    COMPLETE_FLOOR("completeFloor"),
    @XmlEnumValue("mixedUsage")
    MIXED_USAGE("mixedUsage"),
    @XmlEnumValue("statisticsOnly")
    STATISTICS_ONLY("statisticsOnly"),
    @XmlEnumValue("singleParameters")
    SINGLE_PARAMETERS("singleParameters"),
    @XmlEnumValue("other")
    OTHER("other");
    private final String value;

    ParkingTypeOfGroup(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ParkingTypeOfGroup fromValue(String v) {
        for (ParkingTypeOfGroup c: ParkingTypeOfGroup.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
