//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.30 at 03:52:53 PM CEST 
//


package ul.biotope.agents.brussels.jaxb.datex;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PaymentCardBrandsEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PaymentCardBrandsEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="americanExpress"/&gt;
 *     &lt;enumeration value="cirrus"/&gt;
 *     &lt;enumeration value="dinersClub"/&gt;
 *     &lt;enumeration value="discoverCard"/&gt;
 *     &lt;enumeration value="giroCard"/&gt;
 *     &lt;enumeration value="maestro"/&gt;
 *     &lt;enumeration value="masterCard"/&gt;
 *     &lt;enumeration value="visa"/&gt;
 *     &lt;enumeration value="vPay"/&gt;
 *     &lt;enumeration value="other"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "PaymentCardBrandsEnum")
@XmlEnum
public enum PaymentCardBrandsEnum {

    @XmlEnumValue("americanExpress")
    AMERICAN_EXPRESS("americanExpress"),
    @XmlEnumValue("cirrus")
    CIRRUS("cirrus"),
    @XmlEnumValue("dinersClub")
    DINERS_CLUB("dinersClub"),
    @XmlEnumValue("discoverCard")
    DISCOVER_CARD("discoverCard"),
    @XmlEnumValue("giroCard")
    GIRO_CARD("giroCard"),
    @XmlEnumValue("maestro")
    MAESTRO("maestro"),
    @XmlEnumValue("masterCard")
    MASTER_CARD("masterCard"),
    @XmlEnumValue("visa")
    VISA("visa"),
    @XmlEnumValue("vPay")
    V_PAY("vPay"),
    @XmlEnumValue("other")
    OTHER("other");
    private final String value;

    PaymentCardBrandsEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PaymentCardBrandsEnum fromValue(String v) {
        for (PaymentCardBrandsEnum c: PaymentCardBrandsEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
