//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.30 at 03:52:53 PM CEST 
//


package ul.biotope.agents.brussels.jaxb.datex;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for _PointExtensionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="_PointExtensionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="pointExtended" type="{http://datex2.eu/schema/2/2_0}PointExtended" minOccurs="0"/&gt;
 *         &lt;element name="openlrExtendedPoint" type="{http://datex2.eu/schema/2/2_0}OpenlrExtendedPoint" minOccurs="0"/&gt;
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "_PointExtensionType", propOrder = {
    "pointExtended",
    "openlrExtendedPoint",
    "any"
})
public class PointExtensionType {

    protected PointExtended pointExtended;
    protected OpenlrExtendedPoint openlrExtendedPoint;
    @XmlAnyElement(lax = true)
    protected List<Object> any;

    /**
     * Gets the value of the pointExtended property.
     * 
     * @return
     *     possible object is
     *     {@link PointExtended }
     *     
     */
    public PointExtended getPointExtended() {
        return pointExtended;
    }

    /**
     * Sets the value of the pointExtended property.
     * 
     * @param value
     *     allowed object is
     *     {@link PointExtended }
     *     
     */
    public void setPointExtended(PointExtended value) {
        this.pointExtended = value;
    }

    /**
     * Gets the value of the openlrExtendedPoint property.
     * 
     * @return
     *     possible object is
     *     {@link OpenlrExtendedPoint }
     *     
     */
    public OpenlrExtendedPoint getOpenlrExtendedPoint() {
        return openlrExtendedPoint;
    }

    /**
     * Sets the value of the openlrExtendedPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link OpenlrExtendedPoint }
     *     
     */
    public void setOpenlrExtendedPoint(OpenlrExtendedPoint value) {
        this.openlrExtendedPoint = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

}
