//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.30 at 03:52:53 PM CEST 
//


package ul.biotope.agents.brussels.jaxb.datex;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Road complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Road"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="nameOfRoad" type="{http://datex2.eu/schema/2/2_0}MultilingualString" minOccurs="0"/&gt;
 *         &lt;element name="roadIdentifier" type="{http://datex2.eu/schema/2/2_0}MultilingualString" minOccurs="0"/&gt;
 *         &lt;element name="typeOfRoad" type="{http://datex2.eu/schema/2/2_0}RoadTypeEnum" minOccurs="0"/&gt;
 *         &lt;element name="roadDestination" type="{http://datex2.eu/schema/2/2_0}MultilingualString" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="roadOrigination" type="{http://datex2.eu/schema/2/2_0}MultilingualString" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="distanceToThisRoad" type="{http://datex2.eu/schema/2/2_0}MetresAsNonNegativeInteger" minOccurs="0"/&gt;
 *         &lt;element name="roadExtension" type="{http://datex2.eu/schema/2/2_0}_ExtensionType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Road", propOrder = {
    "nameOfRoad",
    "roadIdentifier",
    "typeOfRoad",
    "roadDestination",
    "roadOrigination",
    "distanceToThisRoad",
    "roadExtension"
})
@XmlSeeAlso({
    RoadNode.class
})
public class Road {

    protected MultilingualString nameOfRoad;
    protected MultilingualString roadIdentifier;
    @XmlSchemaType(name = "string")
    protected RoadTypeEnum typeOfRoad;
    protected List<MultilingualString> roadDestination;
    protected List<MultilingualString> roadOrigination;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger distanceToThisRoad;
    protected ExtensionType roadExtension;

    /**
     * Gets the value of the nameOfRoad property.
     * 
     * @return
     *     possible object is
     *     {@link MultilingualString }
     *     
     */
    public MultilingualString getNameOfRoad() {
        return nameOfRoad;
    }

    /**
     * Sets the value of the nameOfRoad property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultilingualString }
     *     
     */
    public void setNameOfRoad(MultilingualString value) {
        this.nameOfRoad = value;
    }

    /**
     * Gets the value of the roadIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link MultilingualString }
     *     
     */
    public MultilingualString getRoadIdentifier() {
        return roadIdentifier;
    }

    /**
     * Sets the value of the roadIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultilingualString }
     *     
     */
    public void setRoadIdentifier(MultilingualString value) {
        this.roadIdentifier = value;
    }

    /**
     * Gets the value of the typeOfRoad property.
     * 
     * @return
     *     possible object is
     *     {@link RoadTypeEnum }
     *     
     */
    public RoadTypeEnum getTypeOfRoad() {
        return typeOfRoad;
    }

    /**
     * Sets the value of the typeOfRoad property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoadTypeEnum }
     *     
     */
    public void setTypeOfRoad(RoadTypeEnum value) {
        this.typeOfRoad = value;
    }

    /**
     * Gets the value of the roadDestination property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the roadDestination property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRoadDestination().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MultilingualString }
     * 
     * 
     */
    public List<MultilingualString> getRoadDestination() {
        if (roadDestination == null) {
            roadDestination = new ArrayList<MultilingualString>();
        }
        return this.roadDestination;
    }

    /**
     * Gets the value of the roadOrigination property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the roadOrigination property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRoadOrigination().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MultilingualString }
     * 
     * 
     */
    public List<MultilingualString> getRoadOrigination() {
        if (roadOrigination == null) {
            roadOrigination = new ArrayList<MultilingualString>();
        }
        return this.roadOrigination;
    }

    /**
     * Gets the value of the distanceToThisRoad property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDistanceToThisRoad() {
        return distanceToThisRoad;
    }

    /**
     * Sets the value of the distanceToThisRoad property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDistanceToThisRoad(BigInteger value) {
        this.distanceToThisRoad = value;
    }

    /**
     * Gets the value of the roadExtension property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionType }
     *     
     */
    public ExtensionType getRoadExtension() {
        return roadExtension;
    }

    /**
     * Sets the value of the roadExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionType }
     *     
     */
    public void setRoadExtension(ExtensionType value) {
        this.roadExtension = value;
    }

}
