//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.30 at 03:52:53 PM CEST 
//


package ul.biotope.agents.brussels.jaxb.datex;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VehicleType2Enum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="VehicleType2Enum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="motorhome"/&gt;
 *     &lt;enumeration value="lightGoodsVehicle"/&gt;
 *     &lt;enumeration value="heavyGoodsVehicle"/&gt;
 *     &lt;enumeration value="minibus"/&gt;
 *     &lt;enumeration value="smallCar"/&gt;
 *     &lt;enumeration value="largeCar"/&gt;
 *     &lt;enumeration value="lightGoodsVehicleWithTrailer"/&gt;
 *     &lt;enumeration value="heavyGoodsVehicleWithTrailer"/&gt;
 *     &lt;enumeration value="heavyHaulageVehicle"/&gt;
 *     &lt;enumeration value="passengerCar"/&gt;
 *     &lt;enumeration value="unknown"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "VehicleType2Enum")
@XmlEnum
public enum VehicleType2Enum {

    @XmlEnumValue("motorhome")
    MOTORHOME("motorhome"),
    @XmlEnumValue("lightGoodsVehicle")
    LIGHT_GOODS_VEHICLE("lightGoodsVehicle"),
    @XmlEnumValue("heavyGoodsVehicle")
    HEAVY_GOODS_VEHICLE("heavyGoodsVehicle"),
    @XmlEnumValue("minibus")
    MINIBUS("minibus"),
    @XmlEnumValue("smallCar")
    SMALL_CAR("smallCar"),
    @XmlEnumValue("largeCar")
    LARGE_CAR("largeCar"),
    @XmlEnumValue("lightGoodsVehicleWithTrailer")
    LIGHT_GOODS_VEHICLE_WITH_TRAILER("lightGoodsVehicleWithTrailer"),
    @XmlEnumValue("heavyGoodsVehicleWithTrailer")
    HEAVY_GOODS_VEHICLE_WITH_TRAILER("heavyGoodsVehicleWithTrailer"),
    @XmlEnumValue("heavyHaulageVehicle")
    HEAVY_HAULAGE_VEHICLE("heavyHaulageVehicle"),
    @XmlEnumValue("passengerCar")
    PASSENGER_CAR("passengerCar"),
    @XmlEnumValue("unknown")
    UNKNOWN("unknown");
    private final String value;

    VehicleType2Enum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static VehicleType2Enum fromValue(String v) {
        for (VehicleType2Enum c: VehicleType2Enum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
